nginx:
  port: 4000
  worker_processes: 4
  ssl : false #put ssl.cert and ssl.key in template folder
  host: "localhost"
  upstreams:
    - name: "upstream1"
      servers:
        - "http://localhost:4000/one"
        - "http://localhost:4000/two"
        - "http://localhost:4000/three"
    - name: "upstream2"
      servers:
        - "http://localhost:8082"
        - "http://localhost:8083"

  proxies:
    - name: "proxy1"
      location: "/proxy1"
      upstream: "https://jsonplaceholder.typicode.com/todos"
    - name: "proxy2"
      location: "/proxy2"
      upstream: "https://www.google.com/"

  render:
    - filename: "one.html"
      location: "/one"
      templatePath: "C:\Use"
    - filename: "two.html"
      location: "/two"
      templatePath: "./templates/two.html"
    - filename: "three.html"
      location: "/three"
      templatePath: "./templates/2.html"

  load_balancer:
    - name: "lb1"
      location: "/l1"
      upstream: "upstream1"
      algorithm: "weighted"
      weight: [2,2,2]
   
